name: Lint

on: [push, pull_request]

jobs:
    lint:
        name: Luacheck
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4.2.2
            - name: Setup
              run: |
                  sudo apt-get update
                  sudo apt-get install luarocks
                  sudo luarocks install luacheck

            - name: Lint
              run: luacheck lua/ --globals vim
